// daftar_lagu.js
window.playlistMap = {
  happy: [
    {
      title: "Evaluasi",
      artist: "Hindia",
      album: "Menari Dengan Bayangan",
      filename: "Evaluasi.mp3",
    },
    {
      title: "Lantas",
      artist: "Juicy Luicy",
      album: "Sentimental",
      filename: "Lantas.mp3",
    },
    {
      title: "Nina",
      artist: ".Feast",
      album: "Membangun dan Menghancurkan",
      filename: "Nina.mp3",
    },
    {
      title: "Best Day of My Life",
      artist: "American Authors",
      album: "Oh, What a Life",
      filename: "Best_Day_Of_My_Life.mp3",
    },
    {
      title: "Good Time",
      artist: "Owl City & Carly Rae Jepsen",
      album: "The Midsummer Station",
      filename: "Good_Time.mp3",
    },
    {
      title: "Bahagia",
      artist: "GAC (Gamaliel Audrey Cantika)",
      album: "Bahagia",
      filename: "Bahagia.mp3",
    },
    {
      title: "Don't Stop Me Now",
      artist: "Queen",
      album: "Jazz",
      filename: "Dont_Stop_Me_Now.mp3",
    },
    {
      title: "Heavy Rotation",
      artist: "JKT48",
      album: "Heavy Rotation",
      filename: "Heavy_Rotation.mp3",
    },
    {
      title: "Smile",
      artist: "Katy Perry",
      album: "Smile",
      filename: "Smile.mp3",
    },
    {
      title: "Something Just Like This",
      artist: "The Chainsmokers ft. Coldplay",
      album: "Memories...Do Not Open",
      filename: "Something_Just_Like_This.mp3",
    },
    {
      title: "Vintage",
      artist: "NIKI",
      album: "Zephyr",
      filename: "Vintage.mp3",
    },
    {
      title: "Firefly",
      artist: "Owl City",
      album: "Ocean Eyes",
      filename: "Firefly.mp3",
    },
  ],
  sad: [
    {
      title: "Hey, I'm Tired",
      artist: "Reality Club",
      album: "Reality Club Presents...",
      filename: "Hey_Im_Tired.mp3",
    },
    {
      title: "Fix You",
      artist: "Coldplay",
      album: "X&Y",
      filename: "Fix_You.mp3",
    },
    {
      title: "About You",
      artist: "The 1975",
      album: "Being Funny in a Foreign Language",
      filename: "About_You.mp3",
    },
    {
      title: "Duka",
      artist: "Last Child",
      album: "Our Biggest Thing Ever",
      filename: "Duka.mp3",
    },
    {
      title: "Serena",
      artist: "HiVi!",
      album: "Kereta Kencan",
      filename: "Serena.mp3",
    },
    {
      title: "Jakarta Hari Ini",
      artist: "Fiersa Besari",
      album: "Konspirasi Alam Semesta",
      filename: "Jakarta_Hari_Ini.mp3",
    },
    {
      title: "Akad",
      artist: "Payung Teduh",
      album: "Payung Teduh",
      filename: "Akad.mp3",
    },
    {
      title: "Someone Like You",
      artist: "Adele",
      album: "21",
      filename: "Someone_Like_You.mp3",
    },
    {
      title: "All I Want",
      artist: "Kodaline",
      album: "In a Perfect World",
      filename: "All_I_Want.mp3",
    },
    {
      title: "Somewhere Only We Know",
      artist: "Keane",
      album: "Hopes and Fears",
      filename: "Somewhere_Only_We_Know.mp3",
    },
    {
      title: "WILDFLOWER",
      artist: "Billie Eilish",
      album: "BILLIE BY FINNEAS",
      filename: "WILDFLOWER.mp3",
    },
    {
      title: "Glimpse of Us",
      artist: "Joji",
      album: "Nectar",
      filename: "Glimpse_of_Us.mp3",
    },
    {
      title: "What Was I Made For?",
      artist: "Billie Eilish",
      album: "Barbie The Album",
      filename: "What_Was_I_Made_For.mp3",
    }
  ],
  angry: [
    {
      title: "Bring Me to Life",
      artist: "Evanescence",
      album: "Fallen",
      filename: "Bring_Me_To_Life.mp3",
    },
    {
      title: "In the End",
      artist: "Linkin Park",
      album: "Hybrid Theory",
      filename: "In_the_End.mp3",
    },
    {
      title: "Bebas",
      artist: "Iwa K",
      album: "Bebas",
      filename: "Bebas.mp3",
    },
    {
      title: "Killing in the Name",
      artist: "Rage Against the Machine",
      album: "Rage Against the Machine",
      filename: "Killing_In_The_Name.mp3",
    },
    {
      title: "Duality",
      artist: "Slipknot",
      album: "Vol. 3: (The Subliminal Verses) ",
      filename: "Duality.mp3",
    },
    {
      title: "Numb",
      artist: "Linkin Park",
      album: "Meteora",
      filename: "Numb.mp3",
    },
    {
      title: "Gunslinger",
      artist: "Avenged Sevenfold",
      album: "Avenged Sevenfold",
      filename: "Gunslinger.mp3",
    },
    {
      title: "Drown",
      artist: "Bring Me the Horizon",
      album: "That's the Spirit",
      filename: "Drown.mp3",
    },
    {
      title: "LosT",
      artist: "Linkin Park",
      album: "Meteora (20th Anniversary Edition)",
      filename: "LosT.mp3",
    },
    {
      title: "Kingslayer",
      artist: "Bring Me the Horizon ft. BABYMETAL",
      album: "Post Human: Survival Horror",
      filename: "Kingslayer.mp3",
    },
    {
      title: "A Little Piece of Heaven",
      artist: "Avenged Sevenfold",
      album: "Avenged Sevenfold",
      filename: "A_Little_Piece_of_Heaven.mp3",
    },
    {
      title: "Strangers",
      artist: "Bring Me the Horizon",
      album: "Single",
      filename: "Strangers.mp3",
    }
  ],
  neutral: [
    {
      title: "Cinta Dalam Hati",
      artist: "Ungu",
      album: "Untukmu Selamanya",
      filename: "Cinta_Dalam_Hati.mp3",
    },
    {
      title: "Let Her Go",
      artist: "Passenger",
      album: "All the Little Lights",
      filename: "Let_Her_Go.mp3",
    },
    {
      title: "Tentang Rasa",
      artist: "Astrid",
      album: "Lihat Aku Sekarang",
      filename: "Tentang_Rasa.mp3",
    },
    {
      title: "Kau Yang Terindah",
      artist: "Java Jive",
      album: "Album Cinta",
      filename: "Kau_Yang_Terindah.mp3",
    },
    {
      title: "The Scientist",
      artist: "Coldplay",
      album: "A Rush of Blood to the Head",
      filename: "The_Scientist.mp3",
    },
    {
      title: "Kesempatan Kedua",
      artist: "Tulus",
      album: "Gajah",
      filename: "Kesempatan_Kedua.mp3",
    },
    {
      title: "Yellow",
      artist: "Coldplay",
      album: "Parachutes",
      filename: "Yellow.mp3",
    },
    {
      title: "Kenangan Manis",
      artist: "Pamungkas",
      album: "Walk The Talk",
      filename: "Kenangan_Manis.mp3",
    },
    {
      title: "As It Was",
      artist: "Harry Styles",
      album: "Harry's House",
      filename: "As_It_Was.mp3",
    },
    {
      title: "Angels Like You",
      artist: "Miley Cyrus",
      album: "Plastic Hearts",
      filename: "Angels_Like_You.mp3",
    },
    {
      title: "Cinnamon Roll",
      artist: "Mckenna Grace",
      album: "Bittersweet 16",
      filename: "Cinnamon_Roll.mp3",
    },
    {
      title: "Dandelions",
      artist: "Ruth B.",
      album: "Safe Haven",
      filename: "Dandelions.mp3",
    }
  ],
  disgusted: [
    {
      title: "Resah",
      artist: "Payung Teduh",
      album: "Dunia Batas",
      filename: "Resah.mp3",
    },
    {
      title: "Desember",
      artist: "Efek Rumah Kaca",
      album: "Efek Rumah Kaca",
      filename: "Desember.mp3",
    },
    {
      title: "December",
      artist: "Neck Deep",
      album: "Life's Not Out to Get You",
      filename: "December.mp3",
    },
    {
      title: "Yang Terlupakan",
      artist: "Iwan Fals",
      album: "Sarjana Muda",
      filename: "Yang_Terlupakan.mp3",
    },
    {
      title: "Smells Like Teen Spirit",
      artist: "Nirvana",
      album: "Nevermind",
      filename: "Smells_Like_Teen_Spirit.mp3",
    },
    {
      title: "Cinta Gila",
      artist: "Dewa 19",
      album: "Republik Cinta",
      filename: "Cinta_Gila.mp3",
    },
    {
      title: "Wish You Were Here",
      artist: "Pink Floyd",
      album: "Wish You Were Here",
      filename: "Wish_You_Were_Here.mp3",
    },
    {
      title: "Line Without a Hook",
      artist: "Ricky Montgomery",
      album: "Montgomery Ricky",
      filename: "Line_Without_a_Hook.mp3",
    },
    {
      title: "Disenchanted",
      artist: "My Chemical Romance",
      album: "The Black Parade",
      filename: "Disenchanted.mp3",
    },
    {
      title: "Seandainya",
      artist: "Vierra",
      album: "My First Love",
      filename: "Seandainya.mp3",
    },
    {
      title: "Tak Segampang Itu",
      artist: "Anggi Marito",
      album: "Tak Segampang Itu (Single)",
      filename: "Tak_Segampang_Itu.mp3",
    },
    {
      title: "Tak Ingin Usai",
      artist: "Keisya Levronka",
      album: "Tak Ingin Usai (Single)",
      filename: "Tak_Ingin_Usai.mp3",
    }
  ],
  surprised: [
    {
      title: "Bersamamu",
      artist: "Vierra",
      album: "My First Love",
      filename: "Bersamamu.mp3",
    },
    {
      title: "Viva La Vida",
      artist: "Coldplay",
      album: "Viva La Vida or Death and All His Friends",
      filename: "Viva_La_Vida.mp3",
    },
    {
      title: "Bohemian Rhapsody",
      artist: "Queen",
      album: "A Night at the Opera",
      filename: "Bohemian_Rhapsody.mp3",
    },
    {
      title: "Counting Stars",
      artist: "OneRepublic",
      album: "Native",
      filename: "Counting_Stars.mp3",
    },
    {
      title: "Feel Good Inc.",
      artist: "Gorillaz",
      album: "Demon Days",
      filename: "Feel_Good_Inc.mp3",
    },
    {
      title: "Sugar",
      artist: "Maroon 5",
      album: "V",
      filename: "Sugar.mp3",
    },
    {
      title: "Tarot",
      artist: "Fleas and Lice feat. Feast",
      album: "Tarot (Single)",
      filename: "Tarot_Feast.mp3",
    },
    {
      title: "Everything U Are",
      artist: "Hindia",
      album: "Lagipula Hidup Akan Berakhir",
      filename: "everything_u_are.mp3",
    },
    {
      title: "The Side of Paradise",
      artist: "Coyote Theory",
      album: "Color",
      filename: "This_Side_of_Paradise.mp3",
    },
    {
      title: "Cincin",
      artist: "Feast",
      album: "Cincin (Single)",
      filename: "Cincin_Feast.mp3",
    },
    {
      title: "Rumah ke Rumah",
      artist: "Hindia",
      album: "Menari Dengan Bayangan",
      filename: "Rumah_Ke_Rumah.mp3",
    },
    {
      title: "Berdansalah, Karir Ini Tidak Ada Artinya",
      artist: "Hindia",
      album: "Menari Dengan Bayangan",
      filename: "Berdansalah,_Karir_Ini_Tidak_Ada_Artinya.mp3",
    }
  ],
  fearful: [
    {
      title: "Dehidrasi",
      artist: "Hindia",
      album: "Menari Dengan Bayangan",
      filename: "Dehidrasi.mp3",
    },
    {
      title: "A Moment Apart",
      artist: "ODESZA",
      album: "A Moment Apart",
      filename: "A_Moment_Apart.mp3",
    },
    {
      title: "Never Be Like You",
      artist: "Flume",
      album: "Skin",
      filename: "Never_Be_Like_You.mp3",
    },
    {
      title: "Bury a Friend",
      artist: "Billie Eilish",
      album: "WHEN WE ALL FALL ASLEEP, WHERE DO WE GO?",
      filename: "bury_a_friend.mp3",
    },
    {
      title: "Shelter",
      artist: "Porter Robinson & Madeon",
      album: "Shelter - Single",
      filename: "Shelter.mp3",
    },
    {
      title: "Dark Paradise",
      artist: "Lana Del Rey",
      album: "Born to Die",
      filename: "Dark_Paradise.mp3",
    },
    {
      title: "Kita Pasti Tua",
      artist: "Fourtwnty",
      album: "Lelaku",
      filename: "Kita_Pasti_Tua.mp3",
    },
    {
      title: "Realita",
      artist: "Fourtwnty",
      album: "Lelaku",
      filename: "Realita.mp3",
    },
    {
      title: "Take Me Somewhere Nice",
      artist: "Mogwai",
      album: "Rock Action",
      filename: "Take_Me_Somewhere_Nice.mp3",
    },
    {
      title: "Bahas Bahasa",
      artist: "Barasuara",
      album: "Tayamum",
      filename: "Bahas_Bahasa.mp3",
    },
    {
      title: "Di Atas Meja",
      artist: "Payung Teduh",
      album: "Tayamum",
      filename: "Di_Atas_Meja.mp3",
    },
    {
      title: "Turn Away and Return",
      artist: "Hammock",
      album: "Everything and Nothing",
      filename: "Turn_Away_and_Return.mp3",
    }
  ],
};